### ISSUE TITLE
Home page content update tab name and video

### ISSUE THREAD

**Issue by ByteGG** [uilibrary/FastAi-Features-and-Issues#3]
Tab header name and slug not updated it stays as Fast AI
![image](https://github.com/uilibrary/FastAi-Features-and-Issues/assets/106935571/c1d821ff-a5bd-48e7-82aa-013e8c99ebf8)

I updated the video and keeps showing the default installation video with the video/image preview that I uploaded.

![image](https://github.com/uilibrary/FastAi-Features-and-Issues/assets/106935571/b79507b7-4dc5-479d-8b3f-f662a6bfe278)

![image](https://github.com/uilibrary/FastAi-Features-and-Issues/assets/106935571/028a8cb7-ac6f-4a02-ae45-a5e204c4a330)

Also the panel logo not updated 

![image](https://github.com/uilibrary/FastAi-Features-and-Issues/assets/106935571/22afc1af-6800-4b55-a6d9-b67b065eade2)

**Comment by jamir-hossain** [comment]
It's not the video update section. This is the video thumbnail update section.
To change the video you have to do it from the first section.
![image](https://github.com/uilibrary/FastAi-Features-and-Issues/assets/61226859/b3d6872b-9b1a-499e-af5d-c3001a9804c9)
Also, we have updated the log or app name change issue. Please update your app to the latest version then you will not face this issue.
