### ISSUE TITLE
Problems with most AI Templates

### ISSUE THREAD

**Issue by simplekod** [uilibrary/FastAi-Features-and-Issues#6]
The completion of the AI is duplicated! It cuts the first completion and continues with the second revision of what it wrote in the first place.
Kindly test it yourself, and you will see (if you read carefully the completion of the AI) that it is messed up. 
Even the token length in my Open AI account is double what each template estimated it would cost. 
Requests also per query are shown as TWO. It looks like the script sends two requests at the same time.

**Comment by jamir-hossain** [comment]
We have fixed this issue. Please update your app to the latest version then you will not face this issue.
